# Python, Numpy, and Vectorization

## 1 Outline

In [1]:
import numpy as np
import time

### 1.1 Goals
### 1.2 Useful References

## 2 Python and Numpy

## 3 Vectors

### 3.1 Abstract
### 3.2 NumPy Arrays

### 3.3 Vector Creation

In [2]:
a= np.zeros(4)
print(f"np.zeros(4): a= {a}, a shape={a.shape}, a data type={a.dtype}")
a= np.zeros((4,))
print(f"np.zeros((4,)): a={a}, a shape={a.shape}, a data type={a.dtype}")
a=np.random.random_sample(4)
print(f"np.random.randm_sample(4): a={a}, a shape={a.shape}, a data type: {a.dtype}")

np.zeros(4): a= [0. 0. 0. 0.], a shape=(4,), a data type=float64
np.zeros((4,)): a=[0. 0. 0. 0.], a shape=(4,), a data type=float64
np.random.randm_sample(4): a=[0.41305416 0.8308872  0.29901859 0.98546072], a shape=(4,), a data type: float64


In [3]:
a=np.arange(4.)
print(f"np.arange(4.): a={a}, a shape={a.shape}, a data type={a.dtype}")
a=np.random.rand(4)
print(f"np.random.rand(4): a={a}, a shape={a.shape}, a data type={a.dtype}")

np.arange(4.): a=[0. 1. 2. 3.], a shape=(4,), a data type=float64
np.random.rand(4): a=[0.96067777 0.29856955 0.90343727 0.23889237], a shape=(4,), a data type=float64


In [4]:
a=np.array([5,4,3,2])
print(f"np.array([5,4,3,2]): a={a}, a shape={a.shape}, a data type={a.dtype}")
a=np.array([5.,4,3,2])
print(f"np.array([5.,4,3,2]): a={a}, a shape={a.shape}, a data type={a.dtype}")

np.array([5,4,3,2]): a=[5 4 3 2], a shape=(4,), a data type=int32
np.array([5.,4,3,2]): a=[5. 4. 3. 2.], a shape=(4,), a data type=float64


### 3.4 Operations on Vectors

#### 3.4.1: Indexing

In [5]:
a=np.arange(10)
a

print(f"a[2].shape: {a[2].shape} a[2]={a[2]}, Accessing an element returns a scalar")
print(f"a[-1]={a[-1]}")
try:
    c=a[10]
except Exception as e:
    print("The error message yo'll see is:")
    print(e)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

a[2].shape: () a[2]=2, Accessing an element returns a scalar
a[-1]=9
The error message yo'll see is:
index 10 is out of bounds for axis 0 with size 10


#### 3.4.2 Slicing

In [6]:
a=np.arange(10); print(f"a={a}")
c=a[2:7:1]; print("a[2:7:1]= ",c)
c=a[2:7:2]; print("a[2:7:2]= ",c)
c=a[3:]; print("a[3:]= ",c)
c=a[:3]; print("a[:3]= ",c)
c=a[:]; print("a[:]= ",c)

a=[0 1 2 3 4 5 6 7 8 9]
a[2:7:1]=  [2 3 4 5 6]
a[2:7:2]=  [2 4 6]
a[3:]=  [3 4 5 6 7 8 9]
a[:3]=  [0 1 2]
a[:]=  [0 1 2 3 4 5 6 7 8 9]


### 3.4.3 Single vector operations

In [7]:
a=np.array([1,2,3,4])
print(f"a:{a}")

b=-a
print(f"b=-a:{b}")

b=np.sum(a)
print(f"b=np.sum(a):{b}")

b=np.mean(a)
print(f"b=np.mean(a):{b}")

b=a**2
print(f"b=a**2:{b}")

a:[1 2 3 4]
b=-a:[-1 -2 -3 -4]
b=np.sum(a):10
b=np.mean(a):2.5
b=a**2:[ 1  4  9 16]


#### 3.4.4 Vector Vector element-wise operations

In [8]:
a=np.array([1,2,3,4])
b=np.array([-1,-2,3,4])
print(f"{a+b}")

[0 0 6 8]


In [9]:
#try a mismatched vector operation
c = np.array([1, 2])
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is:")
    print(e)

The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 


#### 3.4.5 Scalar Vector Operations

In [10]:
a=np.array([1,2,3,4])
b=5*a
print(f"b=5*a={b}")

b=5*a=[ 5 10 15 20]


#### 3.4.6 Vector Vector dot product

In [11]:
def my_dot(a,b):
    """
    Compute the dot product of two vectors

    Args:
        a (ndarray(n,)): input vector
        b (ndarray(n,)): input vector with same dimension as a
    Returns:
        x(scalar)
    """

    x=0
    for i in range(a.shape[0]):
        x=x+a[i]*b[i]
    return x

In [12]:
a=np.array([1,2,3,4])
b=np.array([-1,4,3,2])
print(f"my_dot(a,b): {my_dot(a,b)}")

my_dot(a,b): 24


In [13]:
c = np.dot(a, b)
print(f"NumPy 1-D np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape} ") 
c = np.dot(b, a)
print(f"NumPy 1-D np.dot(b, a) = {c}, np.dot(a, b).shape = {c.shape} ")

NumPy 1-D np.dot(a, b) = 24, np.dot(a, b).shape = () 
NumPy 1-D np.dot(b, a) = 24, np.dot(a, b).shape = () 


#### 3.4.7 The Need for Speed: vectors vs for loop

In [14]:
np.random.seed(1)
a=np.random.rand(100000000)
b=np.random.rand(100000000)
tic=time.time()
c=np.dot(a,b)
toc=time.time()
print(f"np.dot(a,b)={c:.4f}")
print(f"Vectorized version duration:{1000*(toc-tic):.4f} ms")
tic=time.time()
c=my_dot(a,b)
toc=time.time()
print(f"my_dot(a,b)={c:.4f}")
print(f"loop version duration:{1000*(toc-tic):.4f} ms")
del(a)
del(b)

np.dot(a,b)=25000669.8073
Vectorized version duration:58.5241 ms
my_dot(a,b)=25000669.8073
loop version duration:29468.8745 ms


#### 3.4.8 Vector Vector operations in Course 1

In [15]:
X=np.array([[1],[2],[3],[4]])
w=np.array([2])
c=np.dot(X[1],w)

print(f"X[1] has shape {X[1].shape}")
print(f"w has shape {w.shape}")
print(f"c has shape {c.shape}")

X
w
c

X[1] has shape (1,)
w has shape (1,)
c has shape ()


array([[1],
       [2],
       [3],
       [4]])

array([2])

4

## 4 Matrices

### 4.1 Abstract

### 4.2 NumPy Arrays

### 4.3 Matrix Creation

In [17]:
a = np.zeros((1, 5))                                       
print(f"a shape = {a.shape}, a = {a}")                     
a
a = np.zeros((2, 1))                                                                   
print(f"a shape = {a.shape}, a = {a}") 
a
a = np.random.random_sample((1, 1))  
print(f"a shape = {a.shape}, a = {a}") 
a

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]


array([[0., 0., 0., 0., 0.]])

a shape = (2, 1), a = [[0.]
 [0.]]


array([[0.],
       [0.]])

a shape = (1, 1), a = [[0.11907518]]


array([[0.11907518]])

In [18]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([[5], [4], [3]]);   print(f" a shape = {a.shape}, np.array: a = {a}")
a
a = np.array([[5],   # One can also
              [4],   # separate values
              [3]]); #into separate rows
print(f" a shape = {a.shape}, np.array: a = {a}")
a

 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


array([[5],
       [4],
       [3]])

 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


array([[5],
       [4],
       [3]])

### 4.4 Operations on Matrices
#### 4.1 Indexing

In [21]:
a=np.arange(6).reshape(-1,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [23]:
np.arange(6).reshape(2,-1)

array([[0, 1, 2],
       [3, 4, 5]])

In [24]:
a[2,0]
a[2]

4

array([4, 5])

In [26]:
a[2,0].shape
a[2].shape

()

(2,)

In [27]:
a[2,0].dtype
a[2].dtype

dtype('int32')

dtype('int32')

In [29]:
type(a[2,0])
type(a[2])

numpy.int32

numpy.ndarray

#### 4.2.2 Slicing

In [30]:
a=np.arange(20).reshape(-1,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [32]:
a[0,2:7:1]

array([2, 3, 4, 5, 6])

In [36]:
a[0,2:7:1].shape

(5,)

In [33]:
a[:,2:7:1]

array([[ 2,  3,  4,  5,  6],
       [12, 13, 14, 15, 16]])

In [34]:
a[:,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [35]:
a[1,]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [37]:
a[1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])